FROM ubuntu:22.04

LABEL maintainer="Erwin Dondorp <saltgui@dondorp.com>"
LABEL name=salt-master
LABEL project="SaltGUI testing"
LABEL version=3006

ENV SALT_VERSION=3006
ENV DEBIAN_FRONTEND=noninteractive

# add saltstack key and install dependencies
RUN apt-get update \
  && apt-get install curl net-tools gnupg2 dirmngr ca-certificates --yes --no-install-recommends \
  && curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg \
  && echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/${SALT_VERSION} jammy main" | tee /etc/apt/sources.list.d/salt.list \
  && apt-get update \
  && apt-get install salt-master salt-api python3-cherrypy3 --yes --no-install-recommends \
  && apt-get install supervisor --yes --no-install-recommends \
  && dpkg -l | grep salt- \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get -y autoremove \
  && apt-get clean

# copy supervisord configuration
COPY ./conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# some volume configuration for the saltmaster
VOLUME ["/pki", "/var/cache/salt", "/var/log/salt"]
EXPOSE 3333 4505 4506

# define main container command
CMD /usr/bin/supervisord
